"""Build notebooks/07_when_your_simulation_is_lying.ipynb"""

import nbformat as nbf
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
import os

nb = new_notebook()
cells = []
md = lambda s: cells.append(new_markdown_cell(s))
code = lambda s: cells.append(new_code_cell(s))

md(
    "# 07 -- When your simulation is lying to you\n"
    "\n"
    "**This is the part almost nobody teaches. It is the reason this repo exists.**\n"
    "\n"
    "A learned potential is only valid within the distribution of its training data. Outside that distribution -- a configuration never seen during training -- it produces a number. It does not refuse. It does not warn. The number can be wildly wrong.\n"
    "\n"
    "The danger is that a trajectory with wrong forces can still look perfectly normal: atoms move, energies fluctuate, temperature is stable. The simulation passes every naive sanity check and is physically nonsense.\n"
    "\n"
    "This notebook teaches you how to catch it. The tools are:\n"
    "\n"
    "1. **The force-gradient check** (from Notebook 01) -- the first thing you always run.\n"
    "2. **Energy conservation** -- if total energy drifts, the forces or timestep are wrong.\n"
    "3. **Committee models / uncertainty quantification** -- train an ensemble; when the members disagree, you are out-of-distribution.\n"
    "4. **Distance to training set** -- flag configurations that are far from anything seen during training.\n"
    "\n"
    "> **Prerequisites:** Notebooks 01-05."
)

code(
    "import numpy as np\n"
    "import torch\n"
    "import torch.nn as nn\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "from afs.md import (\n"
    "    lj_energy, lj_forces, triangular_lattice,\n"
    "    disk_cluster, thermal_velocities, run_md,\n"
    ")\n"
    "\n"
    "torch.manual_seed(0)\n"
    "np.random.seed(0)"
)

md(
    "## 1. Manufacturing a lying simulation\n"
    "\n"
    "First, let us deliberately create the failure mode. We will train a neural-network potential on configurations where all atoms are at least 1.0 apart (comfortable LJ distances), then run MD at high temperature until two atoms get very close -- a configuration the model has never seen.\n"
    "\n"
    "The model will produce forces that are smooth and plausible-looking. The MD will run. The trajectory will look fine. But the physics is wrong."
)

code(
    "# Train a simple MLP potential on a restricted range of distances\n"
    "def pairwise_distances(pos):\n"
    "    n = len(pos)\n"
    "    return np.sort([np.linalg.norm(pos[i] - pos[j])\n"
    "                    for i in range(n) for j in range(i+1, n)])\n"
    "\n"
    "# Dataset: only safe configs (all pairs > 1.0). We draw perturbed lattices and\n"
    "# keep the ones that stay in the comfortable range -- a small rejection sampler.\n"
    "N_TRAIN   = 1000          # configs we actually train on\n"
    "MAX_TRIES = 500_000       # safety cap so a bad filter can never hang the notebook\n"
    "base = triangular_lattice(3, 3)\n"
    "rng  = np.random.default_rng(42)\n"
    "X_safe, Y_safe = [], []\n"
    "print(f'Generating {N_TRAIN} safe training configs (rejection sampling, ~10s)...')\n"
    "tries = 0\n"
    "while len(Y_safe) < N_TRAIN and tries < MAX_TRIES:\n"
    "    tries += 1\n"
    "    pos = base + 0.18 * rng.standard_normal(base.shape)\n"
    "    dists = pairwise_distances(pos)\n"
    "    if dists.min() > 1.0 and abs(lj_energy(pos)) < 30:  # only safe configs\n"
    "        X_safe.append(dists)\n"
    "        Y_safe.append(lj_energy(pos))\n"
    "if len(Y_safe) < N_TRAIN:\n"
    "    raise RuntimeError(f'only {len(Y_safe)}/{N_TRAIN} safe configs in {MAX_TRIES} draws -- loosen the filter')\n"
    "X_safe = np.array(X_safe); Y_safe = np.array(Y_safe)\n"
    "print(f'Safe dataset: {len(Y_safe)} configs from {tries} draws, min dist in training: {X_safe.min():.3f}')\n"
    "\n"
    "# Train\n"
    "model_unsafe = nn.Sequential(\n"
    "    nn.Linear(36, 64), nn.SiLU(),\n"
    "    nn.Linear(64, 64), nn.SiLU(),\n"
    "    nn.Linear(64, 1),\n"
    ")\n"
    "opt = torch.optim.Adam(model_unsafe.parameters(), lr=3e-3)\n"
    "Xtr = torch.tensor(X_safe[:1000], dtype=torch.float32)\n"
    "ytr = torch.tensor(Y_safe[:1000], dtype=torch.float32)\n"
    "for _ in range(400):\n"
    "    opt.zero_grad()\n"
    "    loss = nn.functional.mse_loss(model_unsafe(Xtr).squeeze(), ytr)\n"
    "    loss.backward(); opt.step()\n"
    "print('Model trained on safe configs only.')"
)

code(
    "# Run MD at high temperature -- atoms will eventually get too close\n"
    "def nn_energy_unsafe(pos_np):\n"
    "    feat = torch.tensor(pairwise_distances(pos_np), dtype=torch.float32).unsqueeze(0)\n"
    "    model_unsafe.eval()\n"
    "    with torch.no_grad():\n"
    "        return model_unsafe(feat).item()\n"
    "\n"
    "def nn_forces_unsafe(pos_np):\n"
    "    pos = torch.tensor(pos_np, dtype=torch.float32, requires_grad=True)\n"
    "    n = len(pos_np)\n"
    "    dists = []\n"
    "    for i in range(n):\n"
    "        for j in range(i+1, n):\n"
    "            diffs = pos[i] - pos[j]\n"
    "            dists.append(torch.sqrt((diffs*diffs).sum()))\n"
    "    feat = torch.stack(sorted(dists, key=lambda t: t.item())).unsqueeze(0)\n"
    "    model_unsafe.eval()\n"
    "    E = model_unsafe(feat)\n"
    "    E.backward()\n"
    "    return -pos.grad.numpy()\n"
    "\n"
    "# High-temperature MD\n"
    "start_pos = triangular_lattice(3, 3)\n"
    "start_vel = thermal_velocities(9, d=2, temp=1.5, seed=99)  # very hot!\n"
    "\n"
    "pos = start_pos.copy(); vel = start_vel.copy()\n"
    "forces = nn_forces_unsafe(pos)\n"
    "dt = 0.003\n"
    "\n"
    "history_pos, history_min_dist, history_E, history_E_LJ = [], [], [], []\n"
    "for step in range(600):\n"
    "    # velocity-Verlet\n"
    "    v_half = vel + 0.5 * forces * dt\n"
    "    pos    = pos + v_half * dt\n"
    "    forces = nn_forces_unsafe(pos)\n"
    "    vel    = v_half + 0.5 * forces * dt\n"
    "\n"
    "    min_d = pairwise_distances(pos).min()\n"
    "    history_pos.append(pos.copy())\n"
    "    history_min_dist.append(min_d)\n"
    "    history_E.append(nn_energy_unsafe(pos) + 0.5 * np.sum(vel**2))\n"
    "    history_E_LJ.append(lj_energy(pos) + 0.5 * np.sum(vel**2))\n"
    "\n"
    "history_min_dist = np.array(history_min_dist)\n"
    "print(f'Minimum pair distance reached: {history_min_dist.min():.3f}')\n"
    "print(f'Training data minimum was:     {X_safe.min():.3f}')\n"
    "ood_step = np.argmin(history_min_dist > 1.0)  # first step below training range\n"
    "print(f'Out-of-distribution step:      {ood_step}')"
)

code(
    "fig, axes = plt.subplots(1, 3, figsize=(14, 4))\n"
    "\n"
    "ax = axes[0]\n"
    "ax.plot(history_min_dist, lw=1.5)\n"
    "ax.axhline(X_safe.min(), color='red', ls='--', label='training min dist')\n"
    "ax.set_xlabel('step'); ax.set_ylabel('min pair distance')\n"
    "ax.set_title('Pair distance: when do we go OOD?')\n"
    "ax.legend()\n"
    "\n"
    "ax = axes[1]\n"
    "ax.plot(history_E,    label='NN total energy', lw=1.5)\n"
    "ax.plot(history_E_LJ, label='True (LJ) total energy', lw=1.5, ls='--')\n"
    "ax.set_xlabel('step'); ax.set_ylabel('energy')\n"
    "ax.set_title('NN energy vs ground truth')\n"
    "ax.legend()\n"
    "\n"
    "ax = axes[2]\n"
    "ax.plot(np.array(history_E) - np.array(history_E_LJ), color='red', lw=1.5)\n"
    "ax.set_xlabel('step'); ax.set_ylabel('NN energy - true energy')\n"
    "ax.set_title('Error grows when atoms get close')\n"
    "\n"
    "plt.tight_layout(); plt.show()\n"
    "\n"
    "print('The NN energy looks plausible but diverges from the truth once min dist < training range.')"
)

md(
    "## 2. Diagnostic 1: the force-gradient check\n"
    "\n"
    "The force-gradient check (from Notebook 01) detects one specific failure: **the forces are not the gradient of the energy**. This happens if there is a bug in the force computation, or if the energy model is non-differentiable.\n"
    "\n"
    "It does NOT catch wrong-but-smooth predictions. But it is fast, cheap, and should always be your first check."
)

code(
    "def force_gradient_check(energy_fn, force_fn, pos, h=1e-4, atol=1e-2):\n"
    "    \"\"\"Check that force_fn == -d(energy_fn)/d(pos) at a given configuration.\"\"\"\n"
    "    analytic = force_fn(pos)\n"
    "    numerical = np.zeros_like(pos)\n"
    "    for i in range(pos.shape[0]):\n"
    "        for k in range(pos.shape[1]):\n"
    "            pp, pm = pos.copy(), pos.copy()\n"
    "            pp[i, k] += h; pm[i, k] -= h\n"
    "            numerical[i, k] = -(energy_fn(pp) - energy_fn(pm)) / (2 * h)\n"
    "    max_err = np.max(np.abs(analytic - numerical))\n"
    "    passed  = max_err < atol\n"
    "    return passed, max_err\n"
    "\n"
    "# Test at a safe configuration\n"
    "pos_safe = triangular_lattice(3, 3) + 0.05 * np.random.randn(9, 2)\n"
    "ok, err = force_gradient_check(nn_energy_unsafe, nn_forces_unsafe, pos_safe)\n"
    "print(f'Force gradient check (safe config): passed={ok}, max_err={err:.6f}')\n"
    "\n"
    "# Test at an unsafe configuration (atoms too close)\n"
    "pos_ood = triangular_lattice(3, 3).copy()\n"
    "pos_ood[0] = pos_ood[1] + np.array([0.3, 0.0])  # two atoms very close\n"
    "ok2, err2 = force_gradient_check(nn_energy_unsafe, nn_forces_unsafe, pos_ood)\n"
    "print(f'Force gradient check (OOD config):  passed={ok2}, max_err={err2:.6f}')\n"
    "print()\n"
    "print('Note: force-gradient check may STILL PASS even when energy is wrong.')\n"
    "print('The forces can be wrong in absolute terms but still be -dE/dr.')"
)

md(
    "## 3. Diagnostic 2: committee model uncertainty\n"
    "\n"
    "The most practical uncertainty estimator for MLPs is a **committee** (ensemble): train $K$ identical networks with different random seeds. At prediction time, run all $K$ networks and compute the standard deviation of their predictions.\n"
    "\n"
    "When the input is in-distribution, the members agree. When the input is out-of-distribution, they disagree -- they each extrapolate differently from the training data.\n"
    "\n"
    "The standard deviation across committee members is a proxy for epistemic uncertainty: how much does the model not know?"
)

code(
    "# Train a committee of 5 models\n"
    "def train_one(seed, Xtr, ytr, epochs=400):\n"
    "    torch.manual_seed(seed)\n"
    "    net = nn.Sequential(\n"
    "        nn.Linear(36, 64), nn.SiLU(),\n"
    "        nn.Linear(64, 64), nn.SiLU(),\n"
    "        nn.Linear(64, 1),\n"
    "    )\n"
    "    opt = torch.optim.Adam(net.parameters(), lr=3e-3)\n"
    "    for _ in range(epochs):\n"
    "        opt.zero_grad()\n"
    "        loss = nn.functional.mse_loss(net(Xtr).squeeze(), ytr)\n"
    "        loss.backward(); opt.step()\n"
    "    return net\n"
    "\n"
    "print('Training committee of 5 models...')\n"
    "committee = [train_one(s, Xtr, ytr) for s in range(5)]\n"
    "print('Committee trained.')\n"
    "\n"
    "\n"
    "def committee_predict(pos_np):\n"
    "    \"\"\"Return (mean_energy, std_energy) from committee.\"\"\"\n"
    "    feat = torch.tensor(pairwise_distances(pos_np), dtype=torch.float32).unsqueeze(0)\n"
    "    preds = []\n"
    "    for net in committee:\n"
    "        net.eval()\n"
    "        with torch.no_grad():\n"
    "            preds.append(net(feat).item())\n"
    "    return np.mean(preds), np.std(preds)\n"
    "\n"
    "\n"
    "# Evaluate committee uncertainty along the MD trajectory\n"
    "stds = []\n"
    "for pos in history_pos[::10]:   # every 10th frame\n"
    "    _, std = committee_predict(pos)\n"
    "    stds.append(std)\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(11, 4))\n"
    "\n"
    "steps_sampled = np.arange(0, len(history_pos), 10)\n"
    "ax = axes[0]\n"
    "ax.plot(steps_sampled, stds, lw=1.5, color='darkorange')\n"
    "ax.axhline(0.1, color='red', ls='--', label='alarm threshold')\n"
    "ax.set_xlabel('MD step'); ax.set_ylabel('committee std (energy)')\n"
    "ax.set_title('Committee uncertainty along trajectory')\n"
    "ax.legend()\n"
    "\n"
    "ax = axes[1]\n"
    "ax.scatter(history_min_dist[::10], stds, alpha=0.5, s=15)\n"
    "ax.axvline(X_safe.min(), color='red', ls='--', label='training min dist')\n"
    "ax.set_xlabel('min pair distance'); ax.set_ylabel('committee std')\n"
    "ax.set_title('Uncertainty vs distance (correlation = red flag detector)')\n"
    "ax.legend()\n"
    "\n"
    "plt.tight_layout(); plt.show()\n"
    "\n"
    "print(f'Max committee std: {max(stds):.4f}')\n"
    "print('When std spikes, the model is in unknown territory.')"
)

md(
    "## 4. Diagnostic 3: distance to training set\n"
    "\n"
    "A complementary approach: measure how far the current configuration is from the nearest training example in feature space. If the distance is large, we are extrapolating.\n"
    "\n"
    "This is simpler to implement than a committee but requires storing the training features. For a production system you would use an approximate nearest-neighbour search; here we use brute force."
)

code(
    "# Compute distance to training set for each trajectory frame\n"
    "def dist_to_training(pos_np, X_train_feat, k=5):\n"
    "    \"\"\"Mean distance to the k nearest training examples in feature space.\"\"\"\n"
    "    feat = pairwise_distances(pos_np)\n"
    "    diffs = X_train_feat - feat  # (n_train, n_feat)\n"
    "    dists = np.linalg.norm(diffs, axis=1)  # (n_train,)\n"
    "    return np.sort(dists)[:k].mean()\n"
    "\n"
    "\n"
    "print('Computing distances to training set (may take 30 s)...')\n"
    "d_to_train = [\n"
    "    dist_to_training(pos, X_safe[:1000])\n"
    "    for pos in history_pos[::10]\n"
    "]\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(11, 4))\n"
    "\n"
    "ax = axes[0]\n"
    "ax.plot(steps_sampled, d_to_train, lw=1.5, color='steelblue')\n"
    "ax.set_xlabel('MD step'); ax.set_ylabel('dist to 5-NN in training set')\n"
    "ax.set_title('Distance to training distribution along trajectory')\n"
    "\n"
    "ax = axes[1]\n"
    "ax.scatter(d_to_train, stds, alpha=0.5, s=15)\n"
    "ax.set_xlabel('dist to training set'); ax.set_ylabel('committee std')\n"
    "ax.set_title('Committee uncertainty vs distance to training')\n"
    "\n"
    "plt.tight_layout(); plt.show()\n"
    "\n"
    "corr = np.corrcoef(d_to_train, stds)[0, 1]\n"
    "print(f'Correlation between distance-to-training and committee std: {corr:.3f}')\n"
    "print('High correlation confirms both signals detect the same OOD regime.')"
)

md(
    "## 5. The OOD protocol: a practical checklist\n"
    "\n"
    "Combining what we have learned, here is a minimal protocol for running a trustworthy ML-MD simulation:\n"
    "\n"
    "**Before running:**\n"
    "1. **Force-gradient check** on the starting configuration and a few random ones. If this fails, something is wrong with the force computation itself.\n"
    "\n"
    "**During the run:**\n"
    "2. **Monitor energy conservation.** If total energy drifts > ~1%, reduce the timestep or check for integration errors.\n"
    "3. **Monitor committee uncertainty** (or distance to training set) every $N$ steps. If the uncertainty exceeds a threshold, stop and flag.\n"
    "\n"
    "**After the run:**\n"
    "4. **Retroactively plot uncertainty vs. time.** Spikes indicate frames to re-run with a more accurate method (DFT).\n"
    "5. **If you find OOD frames, add them to the training set** (active learning) and retrain. Repeat until the uncertainty stays below the threshold.\n"
    "\n"
    "This last loop -- run, flag, retrain -- is called **active learning** or **on-the-fly training**, and it is how modern foundation models are fine-tuned for specific applications."
)

code(
    "# Simulate a run with on-the-fly stopping when uncertainty is too high\n"
    "UNCERTAINTY_THRESHOLD = np.percentile(stds, 85)  # flag top 15% uncertain frames\n"
    "print(f'Uncertainty threshold: {UNCERTAINTY_THRESHOLD:.4f}')\n"
    "\n"
    "pos = start_pos.copy(); vel = start_vel.copy()\n"
    "forces = nn_forces_unsafe(pos)\n"
    "flagged_steps = []\n"
    "\n"
    "for step in range(600):\n"
    "    v_half = vel + 0.5 * forces * dt\n"
    "    pos    = pos + v_half * dt\n"
    "    forces = nn_forces_unsafe(pos)\n"
    "    vel    = v_half + 0.5 * forces * dt\n"
    "\n"
    "    # Check uncertainty every 20 steps (cheap)\n"
    "    if step % 20 == 0:\n"
    "        _, unc = committee_predict(pos)\n"
    "        if unc > UNCERTAINTY_THRESHOLD:\n"
    "            flagged_steps.append(step)\n"
    "\n"
    "print(f'Flagged {len(flagged_steps)} checkpoints out of {600 // 20}')\n"
    "print(f'First flag at step {flagged_steps[0] if flagged_steps else \"never\"}')\n"
    "print()\n"
    "print('In practice: flagged frames go to DFT; DFT results re-enter the training set.')"
)

md(
    "## 6. Summary: trust but verify\n"
    "\n"
    "The key lesson is that **a learned potential is only as trustworthy as its training distribution**. Outside that distribution it interpolates -- or rather extrapolates -- silently.\n"
    "\n"
    "The three diagnostic tools:\n"
    "\n"
    "| Diagnostic | What it catches | Cost |\n"
    "|---|---|---|\n"
    "| Force-gradient check | bugs in force computation | cheap |\n"
    "| Energy conservation | wrong forces OR wrong timestep | free (already monitoring) |\n"
    "| Committee uncertainty | out-of-distribution configurations | moderate (train K models) |\n"
    "| Distance to training set | out-of-distribution configurations | cheap at inference |\n"
    "\n"
    "None of these is perfect. But together they catch the vast majority of silent failures.\n"
    "\n"
    "The good news: every tool in this notebook is physics, not magic. The force-gradient check is the same check you learned in Notebook 01. Energy conservation is the same check. The committee is just several copies of the model from Notebook 03. None of this requires a new framework or a special library.\n"
    "\n"
    "### Exercises\n"
    "\n"
    "1. **Calibrate the threshold.** Run many safe simulations and measure the committee uncertainty distribution. Set the threshold at the 95th percentile of in-distribution uncertainty. What fraction of OOD frames does this catch?\n"
    "\n"
    "2. **Active learning toy.** Implement one round of active learning: (a) run MD until flagged, (b) compute the LJ energy at the flagged frame, (c) add it to the training set, (d) retrain, (e) run again. Does the model improve?\n"
    "\n"
    "3. **Failure on MACE-MP.** MACE-MP is a universal model but still has out-of-distribution regions. Can you find one? Try very high-pressure configurations (atoms at 0.5 A apart) or exotic elements (actinides). Does the committee uncertainty (using MACE-MP with multiple random seeds) spike?"
)

nb.cells = cells

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "notebooks",
    "07_when_your_simulation_is_lying.ipynb",
)
with open(OUT, "w") as f:
    nbf.write(nb, f)

print(f"wrote {OUT}")
