"""Build notebooks/02_why_hand_written_potentials_break.ipynb"""

import nbformat as nbf
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
import os

nb = new_notebook()
cells = []
md = lambda s: cells.append(new_markdown_cell(s))
code = lambda s: cells.append(new_code_cell(s))

# ---------------------------------------------------------------------------
md(
    "# 02 -- Why hand-written potentials break\n"
    "\n"
    "**The Lennard-Jones potential works beautifully for argon. It fails almost everywhere else.**\n"
    "\n"
    "In Notebook 01 we built a real MD engine. The energy, force, and integrator all work. "
    "But there is a catch: the physics we chose -- Lennard-Jones -- is a formula we wrote by hand. "
    "That formula captures exactly one thing: a spherically symmetric, two-body interaction dominated "
    "by van der Waals attraction and Pauli repulsion.\n"
    "\n"
    "Real chemistry is more complicated. In this notebook we make that failure concrete:\n"
    "\n"
    "1. we compare Lennard-Jones to a bond-like potential and see what each can model,\n"
    "2. we show that LJ cannot model bond breaking,\n"
    "3. we sketch why angle terms and many-body effects require more than a pair potential.\n"
    "\n"
    "The lesson is not that classical potentials are useless. "
    "The lesson is that *every hand-written potential encodes assumptions*, "
    "and the assumptions eventually break. "
    "That is the gap machine learning fills.\n"
    "\n"
    "> **Prerequisites:** Notebook 01."
)

# ---------------------------------------------------------------------------
code(
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "from afs.md import lj_energy, lj_forces, run_md, disk_cluster, thermal_velocities, triangular_lattice\n"
    "\n"
    "np.random.seed(42)\n"
    "rng = np.random.default_rng(42)"
)

# ---------------------------------------------------------------------------
md(
    "## 1. What Lennard-Jones assumes\n"
    "\n"
    "The LJ potential:\n"
    "\n"
    "$$V_{LJ}(r) = 4\\varepsilon\\left[\\left(\\frac{\\sigma}{r}\\right)^{12}"
    " - \\left(\\frac{\\sigma}{r}\\right)^{6}\\right]$$\n"
    "\n"
    "embeds four assumptions:\n"
    "\n"
    "1. **Pairwise additivity.** Total energy = sum over pairs. No three-body or many-body effects.\n"
    "2. **Spherical symmetry.** Only distance $r$ matters, not direction. No preferred angles.\n"
    "3. **Fixed functional form.** The 12-6 exponents are fixed. The shape cannot adapt.\n"
    "4. **No bond breaking.** There is a single well; separating atoms just makes the potential go to zero.\n"
    "\n"
    "For noble gases like argon these are fine. For everything else they fail in different ways."
)

code(
    "# Compare LJ to a Morse potential (more bond-like)\n"
    "# Morse has a finite dissociation energy and allows bond breaking.\n"
    "\n"
    "def morse_energy(r, D=1.0, alpha=1.5, r0=1.0):\n"
    "    return D * (1 - np.exp(-alpha * (r - r0)))**2 - D\n"
    "\n"
    "r = np.linspace(0.7, 4.0, 500)\n"
    "v_lj    = 4.0 * (r**-12 - r**-6)\n"
    "v_morse = morse_energy(r, D=1.0, alpha=1.8, r0=2**(1/6))\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(11, 4))\n"
    "\n"
    "ax = axes[0]\n"
    "ax.plot(r, np.clip(v_lj, -1.5, 3), label='Lennard-Jones', lw=2.2)\n"
    "ax.plot(r, v_morse, label='Morse (bond-like)', lw=2.2, ls='--')\n"
    "ax.axhline(0, color='gray', lw=0.6)\n"
    "ax.set_ylim(-1.5, 3); ax.set_xlim(0.7, 4.0)\n"
    "ax.set_xlabel('distance r'); ax.set_ylabel('V(r)')\n"
    "ax.set_title('Two pair potentials'); ax.legend()\n"
    "\n"
    "ax = axes[1]\n"
    "ax.plot(r, np.clip(v_lj, -1.5, 1), label='Lennard-Jones', lw=2.2)\n"
    "ax.plot(r, v_morse, label='Morse (bond-like)', lw=2.2, ls='--')\n"
    "ax.axhline(0, color='gray', lw=0.6)\n"
    "ax.set_xlim(0.9, 3.5); ax.set_ylim(-1.4, 0.5)\n"
    "ax.set_xlabel('distance r'); ax.set_ylabel('V(r)')\n"
    "ax.set_title('Well shape: key difference')\n"
    "ax.legend()\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "print('Morse goes to 0 as r -> infinity (bond can break).')\n"
    "print('LJ also goes to 0, but its well depth is tied to its repulsion --')\n"
    "print('not an independent, tunable dissociation energy.')"
)

# ---------------------------------------------------------------------------
md(
    "## 2. Failure mode 1: bonds do not break\n"
    "\n"
    "The most important thing a chemistry potential must do is allow **bonds to form and break** "
    "with the right energetics. Chemical reactions are nothing else.\n"
    "\n"
    "LJ has a well at $r = 2^{1/6}\\sigma$, so it *does* hold two atoms together and *does* resist "
    "being pulled apart: like any pair potential with a well, its tensile force rises as you "
    "separate the atoms, peaks at the inflection of $V$ (for LJ near $r \\approx 1.24\\,\\sigma$), "
    "and then decays back to zero once they are far apart. Morse behaves exactly the same way -- "
    "so the difference between them is **not** that one has a tensile-force peak and the other "
    "does not. Both do, as the force plot below shows.\n"
    "\n"
    "The real difference is in the *shape and tunability* of the well, and that is what makes LJ "
    "a model of van der Waals attraction rather than a chemical bond:\n"
    "\n"
    "- **The dissociation energy is not a free parameter.** LJ's well depth $\\varepsilon$ is the "
    "same $\\varepsilon$ that sets the repulsion, so you cannot choose a bond strength "
    "independently. Morse's $D$ *is* the dissociation energy, tuned on its own.\n"
    "- **The attractive tail is the wrong physics for a bond.** LJ decays as a power law $r^{-6}$ "
    "(long-range van der Waals, correct for closed-shell noble gases); a covalent bond is screened "
    "and decays exponentially, which is what Morse does.\n"
    "- **The repulsion is artificially stiff.** The $r^{-12}$ wall is a computational convenience, "
    "not physics; real repulsion is softer.\n"
    "\n"
    "So LJ is not 'missing the bond-breaking peak' -- it is using van-der-Waals energetics where "
    "chemistry needs a tunable, exponentially-screened bond."
)

code(
    "r = np.linspace(0.9, 4.0, 500)\n"
    "\n"
    "v_lj    = 4.0 * (r**-12 - r**-6)\n"
    "v_morse = morse_energy(r, D=1.0, alpha=1.8, r0=2**(1/6))\n"
    "\n"
    "f_lj    = -np.gradient(v_lj, r)\n"
    "f_morse = -np.gradient(v_morse, r)\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(11, 4))\n"
    "\n"
    "ax = axes[0]\n"
    "ax.plot(r, v_lj,    label='LJ potential',    lw=2)\n"
    "ax.plot(r, v_morse, label='Morse potential', lw=2, ls='--')\n"
    "ax.axhline(0, color='gray', lw=0.5)\n"
    "ax.set_xlim(0.9, 4.0); ax.set_ylim(-1.4, 2)\n"
    "ax.set_xlabel('r'); ax.set_ylabel('V(r)'); ax.set_title('Energy'); ax.legend()\n"
    "\n"
    "ax = axes[1]\n"
    "ax.plot(r, f_lj,    label='LJ force',    lw=2)\n"
    "ax.plot(r, f_morse, label='Morse force', lw=2, ls='--')\n"
    "ax.axhline(0, color='gray', lw=0.5)\n"
    "ax.set_xlim(0.9, 4.0); ax.set_ylim(-5, 5)\n"
    "ax.set_xlabel('r'); ax.set_ylabel('F(r) = -dV/dr')\n"
    "ax.set_title('Force along separation')\n"
    "ax.legend()\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "r_inflection_morse = 2**(1/6) + np.log(2)/1.8\n"
    "r_inflection_lj    = (26/7)**(1/6)          # inflection of V_LJ, in units of sigma\n"
    "print(f'Morse max tensile force near r ~ {r_inflection_morse:.2f}')\n"
    "print(f'LJ    max tensile force near r ~ {r_inflection_lj:.2f}  (LJ has a peak too)')\n"
    "print('Both dissociate to zero; the real differences are the tunable well depth')\n"
    "print('and the tail shape (LJ ~ r^-6 van der Waals vs Morse ~ exponential bond).')"
)

# ---------------------------------------------------------------------------
md(
    "## 3. Failure mode 2: no directionality\n"
    "\n"
    "Water (H2O) is the most important molecule on Earth. "
    "Its two O-H bonds form an angle of about 104.5 degrees. "
    "That angle is why water is a liquid at room temperature, "
    "why it has high surface tension, why it is a good solvent.\n"
    "\n"
    "LJ has no concept of angles. Every atom interacts with every other by the same "
    "spherical formula, regardless of direction.\n"
    "\n"
    "To model water classically, chemists add explicit **angle and bond terms** to the energy:\n"
    "\n"
    "$$V_{FF} = \\sum_{bonds} k_b (r - r_0)^2 + \\sum_{angles} k_{\\theta} (\\theta - \\theta_0)^2"
    " + \\sum_{pairs} V_{LJ}(r) + \\sum_{pairs} \\frac{q_i q_j}{r}$$\n"
    "\n"
    "This is a **force field** -- a recipe with many hand-tuned parameters. "
    "Let us implement a minimal version to see what this buys us -- and where it still breaks."
)

code(
    "# Minimal water geometry (SPC-like model, illustrative only)\n"
    "K_BOND  = 502.0          # spring constant (kJ/mol/nm^2)\n"
    "R0_OH   = 0.1            # equilibrium O-H bond length (nm)\n"
    "K_ANGLE = 628.0          # angle spring constant (kJ/mol/rad^2)\n"
    "THETA0  = np.radians(109.47)   # H-O-H equilibrium angle (tetrahedral)\n"
    "\n"
    "def water_angle(pos_O, pos_H1, pos_H2):\n"
    "    v1 = pos_H1 - pos_O\n"
    "    v2 = pos_H2 - pos_O\n"
    "    cos_theta = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))\n"
    "    return np.arccos(np.clip(cos_theta, -1, 1))\n"
    "\n"
    "def water_energy(pos_O, pos_H1, pos_H2):\n"
    "    r_OH1 = np.linalg.norm(pos_H1 - pos_O)\n"
    "    r_OH2 = np.linalg.norm(pos_H2 - pos_O)\n"
    "    theta = water_angle(pos_O, pos_H1, pos_H2)\n"
    "    E_bond  = 0.5 * K_BOND  * ((r_OH1 - R0_OH)**2 + (r_OH2 - R0_OH)**2)\n"
    "    E_angle = 0.5 * K_ANGLE * (theta - THETA0)**2\n"
    "    return E_bond + E_angle\n"
    "\n"
    "# Place a water molecule at equilibrium\n"
    "O  = np.array([0.0, 0.0])\n"
    "H1 = np.array([ R0_OH * np.sin(THETA0/2), -R0_OH * np.cos(THETA0/2)])\n"
    "H2 = np.array([-R0_OH * np.sin(THETA0/2), -R0_OH * np.cos(THETA0/2)])\n"
    "\n"
    "print(f'Equilibrium energy: {water_energy(O, H1, H2):.6f}  (should be ~0)')\n"
    "print(f'H-O-H angle: {np.degrees(water_angle(O, H1, H2)):.1f} deg  (target: {np.degrees(THETA0):.1f} deg)')\n"
    "\n"
    "# Visualize\n"
    "fig, axes = plt.subplots(1, 2, figsize=(11, 4))\n"
    "\n"
    "ax = axes[0]\n"
    "for H in [H1, H2]:\n"
    "    ax.plot([O[0], H[0]], [O[1], H[1]], 'k-', lw=2, zorder=1)\n"
    "ax.scatter(*O,  s=800, color='red',   label='O', zorder=2, edgecolors='k')\n"
    "ax.scatter(*H1, s=300, color='white', label='H', zorder=2, edgecolors='k')\n"
    "ax.scatter(*H2, s=300, color='white', zorder=2, edgecolors='k')\n"
    "ax.set_aspect('equal')\n"
    "ax.set_title(f'Water molecule (angle = {np.degrees(THETA0):.1f} deg)')\n"
    "ax.legend(); ax.axis('off')\n"
    "\n"
    "# Energy landscape: vary the H-O-H angle\n"
    "angles_deg = np.linspace(60, 180, 200)\n"
    "E_scan = [\n"
    "    water_energy(\n"
    "        O,\n"
    "        np.array([ R0_OH * np.sin(np.radians(a)/2), -R0_OH * np.cos(np.radians(a)/2)]),\n"
    "        np.array([-R0_OH * np.sin(np.radians(a)/2), -R0_OH * np.cos(np.radians(a)/2)])\n"
    "    ) for a in angles_deg\n"
    "]\n"
    "\n"
    "ax = axes[1]\n"
    "ax.plot(angles_deg, E_scan, lw=2.2)\n"
    "ax.axvline(np.degrees(THETA0), color='crimson', ls='--',\n"
    "           label=f'target {np.degrees(THETA0):.0f} deg')\n"
    "ax.set_xlabel('H-O-H angle (deg)'); ax.set_ylabel('energy (arb. units)')\n"
    "ax.set_title('Angle energy landscape: one harmonic bowl')\n"
    "ax.legend()\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ---------------------------------------------------------------------------
md(
    "## 4. The transferability problem\n"
    "\n"
    "Even if we accept all the approximations, classical force fields hit a fundamental wall: "
    "**the parameters fit for one molecule do not transfer to another**.\n"
    "\n"
    "We can tune the O-H spring constant to make the bond vibrate at the right frequency "
    "in an isolated water molecule. But in liquid water, each molecule interacts with its "
    "neighbours and those interactions subtly change the bond's response. In an enzyme "
    "active site, the same water molecule sits next to a metal ion and a charged amino acid -- "
    "everything changes again.\n"
    "\n"
    "Classical force fields patch this by adding more and more terms -- polarisability, "
    "charge-on-spring, multipoles -- and re-fitting parameters for every new environment. "
    "This works but does not scale. Each new material requires a new fit.\n"
    "\n"
    "Let us make this concrete by comparing what different functional forms are needed "
    "for noble gases, ionic materials, and metals."
)

code(
    "r = np.linspace(1.5, 6.0, 400)\n"
    "\n"
    "# Noble gas (argon): LJ is essentially correct\n"
    "v_lj = 4.0 * (r**-12 - r**-6)\n"
    "\n"
    "# Buckingham potential -- alternative for ionic materials\n"
    "# V = A*exp(-B*r) - C/r^6  (softer repulsion, used for NaCl etc.)\n"
    "A, B_buck, C = 8000.0, 4.5, 80.0\n"
    "v_buck = A * np.exp(-B_buck * r) - C / r**6\n"
    "v_buck_norm = v_buck / max(abs(v_buck.min()), 1e-9)  # normalize for display\n"
    "\n"
    "# Finnis-Sinclair style (metals): embedding energy depends on sqrt of density\n"
    "# This is a MANY-BODY effect -- cannot be expressed as a sum of pair terms\n"
    "rho   = np.exp(-2 * (r - 2.0))\n"
    "v_metal = -np.sqrt(rho) + 0.5 * np.exp(-4 * (r - 2.0))\n"
    "v_metal_norm = v_metal / abs(v_metal.min())\n"
    "\n"
    "fig, axes = plt.subplots(1, 3, figsize=(14, 4))\n"
    "\n"
    "configs = [\n"
    "    ('Noble gas (argon)\\nLJ works well',     v_lj,          'argon -- good fit'),\n"
    "    ('Ionic material\\nBuckingham form',       v_buck_norm,   'ionic -- needs tuning'),\n"
    "    ('Metal (Fe, Cu ...)\\nMany-body effect',  v_metal_norm,  'metal -- pair pot. fails'),\n"
    "]\n"
    "\n"
    "for ax, (label, v, note) in zip(axes, configs):\n"
    "    ax.plot(r, np.clip(v, -1.5, 2.0), lw=2.2)\n"
    "    ax.plot(r, np.clip(v_lj, -1.5, 2.0), lw=1.5, ls=':', color='gray', label='LJ (ref)')\n"
    "    ax.axhline(0, color='k', lw=0.4)\n"
    "    ax.set_xlim(1.5, 6.0); ax.set_ylim(-1.5, 2.0)\n"
    "    ax.set_xlabel('r'); ax.set_ylabel('V(r) (norm.)')\n"
    "    ax.set_title(label + f'\\n[{note}]')\n"
    "    ax.legend(fontsize=8)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "print('argon : LJ is a reasonable model (spherical, van der Waals)')\n"
    "print('ionic : need Coulomb terms and different repulsion -- LJ is wrong in detail')\n"
    "print('metal : many-body embedding energy; a pair potential cannot capture')\n"
    "print('        the difference between a surface atom and a bulk atom.')\n"
    "print()\n"
    "print('One formula cannot rule them all.')"
)

# ---------------------------------------------------------------------------
md(
    "## 5. What machine learning gives us -- and what it costs\n"
    "\n"
    "The key insight of machine-learning potentials (MLPs) is simple:\n"
    "\n"
    "> Instead of choosing a functional form by physics intuition and fitting parameters "
    "by hand, let a neural network learn the function from data.\n"
    "\n"
    "The MD loop from Notebook 01 does not change at all:\n"
    "\n"
    "```python\n"
    "forces = lj_forces(positions)   # notebook 01: hand-written formula\n"
    "forces = nn_forces(positions)   # notebook 03: a neural network\n"
    "```\n"
    "\n"
    "The interface is identical. Velocity-Verlet, energy conservation, "
    "and the force-gradient check all carry over unchanged.\n"
    "\n"
    "**What we gain:**\n"
    "- Universality: one architecture can fit any material if trained on the right data.\n"
    "- Accuracy: can approach quantum-chemistry accuracy at a fraction of the cost.\n"
    "- Transferability: if training data covers diverse environments, the potential transfers.\n"
    "\n"
    "**What we pay:**\n"
    "- We need training data (quantum chemistry calculations are expensive).\n"
    "- The potential is only valid within the distribution of its training data. "
    "Outside that distribution it can fail *silently* -- producing a trajectory that "
    "looks fine but is physically wrong. That silent failure is Notebook 07.\n"
    "\n"
    "### Summary: what every hand-written potential cannot do\n"
    "\n"
    "| Assumption | LJ says | Reality says |\n"
    "|---|---|---|\n"
    "| Pairwise only | assumed | many-body effects exist |\n"
    "| Spherically symmetric | assumed | bonds have directions |\n"
    "| Fixed functional form | chosen once | different for every material |\n"
    "| Bond breaking | cannot model | required for chemistry |\n"
    "\n"
    "Every row in that table is something a neural-network potential can, in principle, learn away.\n"
    "\n"
    "### Exercises\n"
    "\n"
    "1. **Morse dynamics.** Implement `morse_forces(positions, D, alpha, r0)` "
    "   using a finite-difference gradient. Run an MD simulation of a diatomic 'molecule' "
    "   starting at 1.5x the equilibrium distance with LJ vs Morse. What happens?\n"
    "\n"
    "2. **Three-body check.** Add a third atom to a triangular configuration. "
    "   Compare LJ energy (pairwise sum) to the Axilrod-Teller three-body correction "
    "   (look up the formula). By what percentage does the pairwise approximation err?\n"
    "\n"
    "3. **Force-field fitting.** Write a function that evaluates the vibrational frequencies "
    "   of the water molecule as a function of K_BOND and K_ANGLE. "
    "   Use scipy.optimize.minimize to fit them to target frequencies. "
    "   What is the trade-off between fitting geometry vs. frequencies?"
)

# ---------------------------------------------------------------------------
nb.cells = cells

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "notebooks",
    "02_why_hand_written_potentials_break.ipynb",
)
with open(OUT, "w") as f:
    nbf.write(nb, f)

print(f"wrote {OUT}")
