"""Build notebooks/05_message_passing_graph_neural_nets.ipynb  (CORRECTED)

Fix vs original: GNNPotential.forward previously did `pos_np = pos_t.detach().numpy()`
and computed all edge distances/RBF features in NumPy, detached from the graph. The
energy therefore had NO gradient dependence on pos_t, so `gnn_forces` computed
`-pos_t.grad.numpy()` with `pos_t.grad is None` -> AttributeError (crash) at the
force-gradient check and the MD cell.

The fix: build the neighbour-list *indices* on detached positions (membership is a
step function, treated as fixed), but recompute the edge displacement vectors and
distances IN TORCH from pos_t, and expand them with a torch RBF. Now the energy
depends on pos_t and autograd yields correct, finite forces.
"""

import nbformat as nbf
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
import os

nb = new_notebook()
cells = []
md = lambda s: cells.append(new_markdown_cell(s))
code = lambda s: cells.append(new_code_cell(s))

md(
    "# 05 -- Message passing (graph neural nets)\n"
    "\n"
    "**Modern potentials are geometry-aware GNNs.**\n"
    "\n"
    "Notebook 04 showed that symmetry functions work -- but they are hand-designed. "
    "The network cannot adjust the representation to fit the data.\n"
    "\n"
    "The key insight of graph neural networks for molecules is:\n"
    "\n"
    "> Represent a molecule as a graph (atoms = nodes, neighbour pairs = edges), then let "
    "the network iteratively update each atom's representation by aggregating messages from "
    "its neighbours.\n"
    "\n"
    "After $T$ rounds of message passing, each atom's embedding encodes information about its "
    "$T$-hop neighbourhood. For $T=3$ or so, that is enough to capture almost any local chemistry.\n"
    "\n"
    "This is what SchNet, DimeNet, NequIP, MACE and all modern foundation models do. "
    "In this notebook we build the core from scratch:\n"
    "1. Represent atoms as a graph with edge features (distances).\n"
    "2. Implement one round of message passing.\n"
    "3. Stack rounds, read out the energy, train, and run MD.\n"
    "\n"
    "> **Prerequisites:** Notebooks 01-04."
)

code(
    "import numpy as np\n"
    "import torch\n"
    "import torch.nn as nn\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "from afs.md import (\n"
    "    lj_energy, lj_forces, triangular_lattice,\n"
    "    disk_cluster, thermal_velocities, run_md,\n"
    ")\n"
    "\n"
    "torch.manual_seed(0)\n"
    "np.random.seed(0)"
)

md(
    "## 1. A molecule is a graph\n"
    "\n"
    "We build an **edge list**: for each pair of atoms within the cutoff radius $r_c$, we add a "
    "directed edge in both directions. Each edge carries the displacement vector and distance.\n"
    "\n"
    "This representation is **sparse** (only nearby pairs matter, cost $O(N)$ not $O(N^2)$), "
    "**permutation-equivariant** (the graph is defined by physical proximity, not atom ordering), "
    "and **translation-invariant** (we store *relative* displacements)."
)

code(
    "def build_graph(pos, r_cut=3.5):\n"
    "    \"\"\"Neighbour-list graph. Returns (src, dst, edge_vec, edge_dist) as numpy arrays.\n"
    "\n"
    "    Only the src/dst *indices* are used downstream for the differentiable model; the\n"
    "    displacement vectors and distances are recomputed in torch inside the model so that\n"
    "    gradients flow back to the atomic positions.\n"
    "    \"\"\"\n"
    "    n = len(pos)\n"
    "    src, dst, vecs, dists = [], [], [], []\n"
    "    for i in range(n):\n"
    "        for j in range(n):\n"
    "            if i == j:\n"
    "                continue\n"
    "            diff = pos[j] - pos[i]\n"
    "            r = np.linalg.norm(diff)\n"
    "            if r < r_cut:\n"
    "                src.append(i); dst.append(j)\n"
    "                vecs.append(diff); dists.append(r)\n"
    "    return (np.array(src), np.array(dst), np.array(vecs), np.array(dists))\n"
    "\n"
    "pos = triangular_lattice(3, 3)\n"
    "src, dst, vecs, dists = build_graph(pos, r_cut=2.5)\n"
    "print(f'9 atoms, {len(src)} directed edges (r_cut=2.5)')\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(5, 5))\n"
    "ax.scatter(pos[:, 0], pos[:, 1], s=300, zorder=5)\n"
    "for s, d in zip(src, dst):\n"
    "    ax.annotate('', xy=pos[d], xytext=pos[s],\n"
    "                arrowprops=dict(arrowstyle='->', color='steelblue', alpha=0.5))\n"
    "ax.set_aspect('equal'); ax.axis('off')\n"
    "ax.set_title(f'Molecular graph: {len(src)} directed edges')\n"
    "plt.tight_layout(); plt.show()"
)

md(
    "## 2. Edge features: expanding distances in a radial basis\n"
    "\n"
    "A scalar distance is too little information per edge. We expand each distance into a vector "
    "using a **radial basis function (RBF)** expansion: a set of Gaussian bumps spread across "
    "$[0, r_c]$. This is the GNN analogue of the radial symmetry functions from Notebook 04, "
    "but the edge features feed into *learned* message functions.\n"
    "\n"
    "> We define the RBF twice: a NumPy version for plotting, and a torch method inside the model "
    "(Section 4) that keeps the autograd graph so forces can be differentiated through it."
)

code(
    "def rbf_expansion(dists, n_rbf=20, r_cut=3.5):\n"
    "    \"\"\"Expand scalar distances into (E, n_rbf) RBF features (numpy, for plotting).\"\"\"\n"
    "    centers = np.linspace(0, r_cut, n_rbf)\n"
    "    width = (r_cut / n_rbf) ** 2\n"
    "    x = dists[:, None]\n"
    "    return np.exp(-((x - centers) ** 2) / width)\n"
    "\n"
    "r_plot = np.linspace(0, 3.5, 200)\n"
    "rbf_plot = rbf_expansion(r_plot, n_rbf=20)\n"
    "plt.figure(figsize=(7, 3))\n"
    "for col in rbf_plot.T:\n"
    "    plt.plot(r_plot, col, lw=1.2, alpha=0.7)\n"
    "plt.xlabel('distance r'); plt.ylabel('RBF value')\n"
    "plt.title('Radial basis functions (20 Gaussians)')\n"
    "plt.tight_layout(); plt.show()"
)

md(
    "## 3. One round of message passing\n"
    "\n"
    "The core operation of a GNN is a **message-passing step**:\n"
    "\n"
    "```\n"
    "for each atom i:\n"
    "    messages = [message_net(h[i], h[j], e_ij) for j in neighbours(i)]\n"
    "    h[i]_new = update_net(h[i], sum(messages))\n"
    "```\n"
    "\n"
    "The messages are **summed** over neighbours (permutation invariance), and `update_net` "
    "combines the old embedding with the aggregated messages. After $T$ rounds, each atom's "
    "embedding encodes its $T$-hop environment."
)

code(
    "class MessagePassingLayer(nn.Module):\n"
    "    \"\"\"One round of message passing with a residual update.\"\"\"\n"
    "    def __init__(self, node_dim, edge_dim):\n"
    "        super().__init__()\n"
    "        self.message_net = nn.Sequential(\n"
    "            nn.Linear(2 * node_dim + edge_dim, node_dim), nn.SiLU(),\n"
    "            nn.Linear(node_dim, node_dim),\n"
    "        )\n"
    "        self.update_net = nn.Sequential(\n"
    "            nn.Linear(2 * node_dim, node_dim), nn.SiLU(),\n"
    "            nn.Linear(node_dim, node_dim),\n"
    "        )\n"
    "\n"
    "    def forward(self, h, edge_src, edge_dst, edge_feat):\n"
    "        h_src = h[edge_src]                       # (E, node_dim)\n"
    "        h_dst = h[edge_dst]                       # (E, node_dim)\n"
    "        inp = torch.cat([h_src, h_dst, edge_feat], dim=-1)\n"
    "        msgs = self.message_net(inp)              # (E, node_dim)\n"
    "        agg = torch.zeros_like(h)\n"
    "        agg.index_add_(0, edge_dst, msgs)         # sum incoming edges\n"
    "        h_new = self.update_net(torch.cat([h, agg], dim=-1))\n"
    "        return h + h_new                          # residual\n"
    "\n"
    "# Quick shape test\n"
    "D_node, D_edge = 32, 20\n"
    "layer = MessagePassingLayer(D_node, D_edge)\n"
    "h_test = torch.randn(9, D_node)\n"
    "edge_feat_t = torch.tensor(rbf_expansion(dists), dtype=torch.float32)\n"
    "src_t = torch.tensor(src, dtype=torch.long)\n"
    "dst_t = torch.tensor(dst, dtype=torch.long)\n"
    "h_out = layer(h_test, src_t, dst_t, edge_feat_t)\n"
    "print(f'Input shape:  {tuple(h_test.shape)}')\n"
    "print(f'Output shape: {tuple(h_out.shape)} (updated, not resized)')"
)

md(
    "## 4. Full GNN potential: message passing + energy readout\n"
    "\n"
    "We stack $T$ message-passing layers, then read out the energy as a sum of per-atom scalar "
    "contributions:\n"
    "\n"
    "$$E = \\sum_{i=1}^{N} \\text{readout}(\\mathbf{h}_i^{(T)})$$\n"
    "\n"
    "Summing per-atom contributions makes the potential **size-extensive**.\n"
    "\n"
    "> **The crucial detail for forces.** The neighbour *list* (which pairs are edges) is built "
    "on detached positions, but the edge **distances** are recomputed in torch directly from "
    "`pos_t`, and expanded with a torch RBF. This keeps `pos_t` in the autograd graph, so "
    "$\\mathbf{F} = -\\partial E/\\partial \\mathbf{r}$ is well defined. (If you build the "
    "distances in NumPy, the energy does not depend on the positions and the forces come back "
    "as `None`.)"
)

code(
    "class GNNPotential(nn.Module):\n"
    "    \"\"\"GNN energy model: T rounds of message passing + per-atom readout.\n"
    "\n"
    "    forward(pos_t) takes an (N, d) torch tensor and returns a scalar energy that is\n"
    "    differentiable w.r.t. pos_t.\n"
    "    \"\"\"\n"
    "    def __init__(self, node_dim=32, n_rbf=20, r_cut=3.5, n_layers=3):\n"
    "        super().__init__()\n"
    "        self.node_dim = node_dim\n"
    "        self.n_rbf = n_rbf\n"
    "        self.r_cut = r_cut\n"
    "        self.atom_embed = nn.Embedding(1, node_dim)   # one species here\n"
    "        self.mp_layers = nn.ModuleList([\n"
    "            MessagePassingLayer(node_dim, n_rbf) for _ in range(n_layers)\n"
    "        ])\n"
    "        self.readout = nn.Sequential(\n"
    "            nn.Linear(node_dim, node_dim // 2), nn.SiLU(),\n"
    "            nn.Linear(node_dim // 2, 1),\n"
    "        )\n"
    "        # RBF centers as a fixed buffer so they move with .to(device)\n"
    "        self.register_buffer('centers', torch.linspace(0, r_cut, n_rbf))\n"
    "        self.width = (r_cut / n_rbf) ** 2\n"
    "\n"
    "    def _rbf_torch(self, edge_dist):\n"
    "        \"\"\"Differentiable RBF expansion of (E,) torch distances -> (E, n_rbf).\"\"\"\n"
    "        x = edge_dist[:, None]                        # (E, 1)\n"
    "        return torch.exp(-((x - self.centers) ** 2) / self.width)\n"
    "\n"
    "    def forward(self, pos_t):\n"
    "        # 1) neighbour list on detached positions (membership is a step function)\n"
    "        pos_np = pos_t.detach().numpy()\n"
    "        e_src, e_dst, _, _ = build_graph(pos_np, self.r_cut)\n"
    "        src_t = torch.tensor(e_src, dtype=torch.long)\n"
    "        dst_t = torch.tensor(e_dst, dtype=torch.long)\n"
    "        N = pos_t.shape[0]\n"
    "\n"
    "        # 2) recompute edge distances IN TORCH so energy depends on positions\n"
    "        edge_vec = pos_t[dst_t] - pos_t[src_t]                     # (E, d), grad kept\n"
    "        edge_dist = torch.sqrt((edge_vec ** 2).sum(dim=1) + 1e-12) # (E,)\n"
    "        edge_f = self._rbf_torch(edge_dist)                        # (E, n_rbf)\n"
    "\n"
    "        # 3) message passing + readout\n"
    "        h = self.atom_embed(torch.zeros(N, dtype=torch.long))\n"
    "        for layer in self.mp_layers:\n"
    "            h = layer(h, src_t, dst_t, edge_f)\n"
    "        atom_energies = self.readout(h).squeeze(-1)                # (N,)\n"
    "        return atom_energies.sum()\n"
    "\n"
    "gnn = GNNPotential(node_dim=32, n_rbf=20, r_cut=3.5, n_layers=3)\n"
    "print(f'GNN parameters: {sum(p.numel() for p in gnn.parameters()):,}')\n"
    "\n"
    "# Sanity: the energy really does depend on positions (gradient is non-zero / not None)\n"
    "p = torch.tensor(triangular_lattice(3, 3), dtype=torch.float32, requires_grad=True)\n"
    "E = gnn(p); E.backward()\n"
    "print('grad is not None:', p.grad is not None)\n"
    "print('grad has non-zero entries:', bool((p.grad.abs() > 0).any()))"
)

md(
    "## 5. Train the GNN and run MD\n"
    "\n"
    "We generate data the same way as before (perturbed LJ clusters), train with energy "
    "supervision, compute forces via autograd, and run MD."
)

code(
    "def make_gnn_dataset(n_samples=800, noise=0.3):\n"
    "    base = triangular_lattice(3, 3)\n"
    "    rng = np.random.default_rng(7)\n"
    "    configs, energies = [], []\n"
    "    while len(energies) < n_samples:\n"
    "        pos = base + noise * rng.standard_normal(base.shape)\n"
    "        E = lj_energy(pos)\n"
    "        if abs(E) < 50:\n"
    "            configs.append(pos.copy()); energies.append(E)\n"
    "    return configs, np.array(energies)\n"
    "\n"
    "print('Generating GNN dataset...')\n"
    "configs, energies = make_gnn_dataset()\n"
    "print(f'{len(configs)} configs')"
)

code(
    "n_val = 150\n"
    "n_train = len(configs) - n_val\n"
    "train_configs, train_E = configs[:n_train], energies[:n_train]\n"
    "val_configs, val_E = configs[n_train:], energies[n_train:]\n"
    "\n"
    "opt = torch.optim.Adam(gnn.parameters(), lr=1e-3)\n"
    "sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=200)\n"
    "\n"
    "train_losses, val_losses = [], []\n"
    "print('Training GNN (this may take ~2 minutes on CPU)...')\n"
    "for epoch in range(200):\n"
    "    gnn.train()\n"
    "    perm = np.random.permutation(n_train)\n"
    "    epoch_loss = 0.0\n"
    "    for b_start in range(0, n_train, 32):\n"
    "        opt.zero_grad()\n"
    "        batch_loss = 0.0\n"
    "        batch_idx = perm[b_start:b_start + 32]\n"
    "        for idx in batch_idx:\n"
    "            pos_t = torch.tensor(train_configs[idx], dtype=torch.float32)\n"
    "            batch_loss = batch_loss + (gnn(pos_t) - train_E[idx]) ** 2\n"
    "        batch_loss = batch_loss / len(batch_idx)\n"
    "        batch_loss.backward()\n"
    "        opt.step()\n"
    "        epoch_loss += batch_loss.item()\n"
    "    train_losses.append(epoch_loss / (n_train / 32))\n"
    "    gnn.eval()\n"
    "    with torch.no_grad():\n"
    "        vl = sum((gnn(torch.tensor(c, dtype=torch.float32)).item() - e) ** 2\n"
    "                 for c, e in zip(val_configs, val_E)) / n_val\n"
    "    val_losses.append(vl); sched.step()\n"
    "    if (epoch + 1) % 50 == 0:\n"
    "        print(f'epoch {epoch+1:3d}  train MSE={train_losses[-1]:.4f}  val MSE={val_losses[-1]:.4f}')\n"
    "\n"
    "plt.figure(figsize=(6, 3))\n"
    "plt.semilogy(train_losses, label='train')\n"
    "plt.semilogy(val_losses, label='val')\n"
    "plt.xlabel('epoch'); plt.ylabel('MSE'); plt.title('GNN training curve')\n"
    "plt.legend(); plt.tight_layout(); plt.show()"
)

code(
    "def gnn_forces(pos_np):\n"
    "    pos_t = torch.tensor(pos_np, dtype=torch.float32, requires_grad=True)\n"
    "    E = gnn(pos_t)\n"
    "    E.backward()\n"
    "    return -pos_t.grad.numpy()\n"
    "\n"
    "def gnn_energy(pos_np):\n"
    "    with torch.no_grad():\n"
    "        return gnn(torch.tensor(pos_np, dtype=torch.float32)).item()\n"
    "\n"
    "# Force-gradient check (now runs -- forces are no longer None)\n"
    "pos_test = triangular_lattice(3, 3) + 0.05 * np.random.randn(9, 2)\n"
    "F_analytic = gnn_forces(pos_test)\n"
    "h = 1e-3\n"
    "F_numerical = np.zeros_like(pos_test)\n"
    "for i in range(pos_test.shape[0]):\n"
    "    for k in range(pos_test.shape[1]):\n"
    "        pp, pm = pos_test.copy(), pos_test.copy()\n"
    "        pp[i, k] += h; pm[i, k] -= h\n"
    "        F_numerical[i, k] = -(gnn_energy(pp) - gnn_energy(pm)) / (2 * h)\n"
    "print(f'GNN force-gradient check: max err = {np.max(np.abs(F_analytic - F_numerical)):.5f}')\n"
    "print(f'autograd == numerical: {np.allclose(F_analytic, F_numerical, atol=1e-2)}')\n"
    "\n"
    "print('Running GNN-MD...')\n"
    "start_pos = triangular_lattice(3, 3)\n"
    "start_vel = thermal_velocities(9, d=2, temp=0.1, seed=3)\n"
    "pos = start_pos.copy(); vel = start_vel.copy()\n"
    "forces = gnn_forces(pos)\n"
    "tot_E, dt, steps = [], 0.003, 300\n"
    "for _ in range(steps):\n"
    "    v_half = vel + 0.5 * forces * dt\n"
    "    pos = pos + v_half * dt\n"
    "    forces = gnn_forces(pos)\n"
    "    vel = v_half + 0.5 * forces * dt\n"
    "    tot_E.append(0.5 * np.sum(vel ** 2) + gnn_energy(pos))\n"
    "\n"
    "drift = (max(tot_E) - min(tot_E)) / abs(np.mean(tot_E))\n"
    "print(f'GNN-MD energy drift: {drift:.3%}')\n"
    "plt.figure(figsize=(6, 3))\n"
    "plt.plot(tot_E)\n"
    "plt.xlabel('MD step'); plt.ylabel('total energy')\n"
    "plt.title(f'GNN-MD energy conservation (drift={drift:.2%})')\n"
    "plt.tight_layout(); plt.show()"
)

md(
    "## 6. What you built and what is next\n"
    "\n"
    "You implemented the core of SchNet, one of the foundational GNN potentials, in about 80 lines "
    "of PyTorch. Scaled up with more layers and width, **equivariant** message passing (features "
    "that transform as tensors under rotation), multi-element embeddings, and training on millions "
    "of DFT configurations, this becomes MACE-MP -- a foundation model that simulates almost any "
    "material zero-shot. That is Notebook 06.\n"
    "\n"
    "**What we simplified:**\n"
    "- Invariant (distance-only) message passing. NequIP and MACE use **equivariant** message "
    "  passing, which is more data-efficient.\n"
    "- No periodic boundary conditions.\n"
    "- Energy-only training; including forces in the loss is standard and accelerates learning.\n"
    "\n"
    "### Exercises\n"
    "\n"
    "1. **Force loss.** Add forces to the training loss (autograd the energy during training). "
    "   How does the MD energy drift change?\n"
    "\n"
    "2. **Deeper network.** Increase `n_layers` from 3 to 5. Does accuracy improve? Does training "
    "   time increase proportionally?\n"
    "\n"
    "3. **Cutoff sensitivity.** Train with `r_cut=2.0` and `r_cut=5.0`. What is the trade-off? "
    "   (Hint: think about what information each atom receives.)"
)

nb.cells = cells
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "notebooks", "05_message_passing_graph_neural_nets.ipynb")
with open(OUT, "w") as f:
    nbf.write(nb, f)
print(f"wrote {OUT}")
