"""Build notebooks/03_neural_network_potential_from_scratch.ipynb  (CORRECTED)

Fix vs original: pairwise_distances_torch now SORTS the distances while keeping
the autograd graph (torch.stack over a value-sorted list of graph tensors), so
the features used for the force (autograd) match the sorted features used for
training and for nn_energy. Previously the torch path returned UNSORTED
distances, making the force the gradient of a different function than the
energy -- the gradient check compared two different functions and the MD force
was inconsistent with the recorded energy.
"""

import nbformat as nbf
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
import os

nb = new_notebook()
cells = []
md = lambda s: cells.append(new_markdown_cell(s))
code = lambda s: cells.append(new_code_cell(s))

md(
    "# 03 -- A neural-network potential from scratch\n"
    "\n"
    "**Energy is a neural net. Forces come free from autograd.**\n"
    "\n"
    "In Notebook 01 we wrote the force by hand. In Notebook 02 we saw why that breaks. "
    "Now we fix it: we keep the entire MD loop unchanged and swap in a neural network "
    "that *learns* the energy from data, with forces computed automatically by differentiation.\n"
    "\n"
    "The idea fits in one sentence:\n"
    "\n"
    "> Train a network to predict $V(\\mathbf{r})$. Then $\\mathbf{F}_i = -\\nabla_{\\mathbf{r}_i} V$ "
    "comes from `torch.autograd`, exactly like the finite-difference check in Notebook 01, "
    "but exact and fast.\n"
    "\n"
    "By the end of this notebook you will have:\n"
    "\n"
    "1. generated training data from the Lennard-Jones potential (so we can check the learned result),\n"
    "2. built and trained a tiny MLP that predicts potential energy,\n"
    "3. computed forces via autograd and verified them with the same gradient check as Notebook 01,\n"
    "4. run a full MD trajectory with the learned potential and confirmed energy conservation.\n"
    "\n"
    "> **Prerequisites:** Notebooks 01 and 02. You need a basic understanding of PyTorch "
    "(`tensor`, `grad_fn`, `backward`)."
)

code(
    "import numpy as np\n"
    "import torch\n"
    "import torch.nn as nn\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "from afs.md import (\n"
    "    lj_energy, lj_forces, run_md,\n"
    "    triangular_lattice, disk_cluster, thermal_velocities,\n"
    ")\n"
    "\n"
    "torch.manual_seed(0)\n"
    "np.random.seed(0)"
)

md(
    "## 1. Generate training data\n"
    "\n"
    "We will train on the Lennard-Jones potential -- not because LJ is interesting, "
    "but because we know the ground truth and can check our work. "
    "The exact same pipeline works for *ab initio* quantum-chemistry data later.\n"
    "\n"
    "**What does training data look like?** Each example is:\n"
    "- **input:** the positions of all atoms -- an $(N, d)$ array,\n"
    "- **label:** the total potential energy -- a single scalar.\n"
    "\n"
    "We sample random configurations by perturbing atoms from a lattice, "
    "compute the LJ energy for each, and collect them into a dataset."
)

code(
    "def make_dataset(n_samples=2000, n_atoms=9, noise_scale=0.3):\n"
    "    \"\"\"\n"
    "    Return (X, y) where\n"
    "        X : (n_samples, n_atoms, 2) -- positions\n"
    "        y : (n_samples,)            -- LJ energies\n"
    "    \"\"\"\n"
    "    base = triangular_lattice(3, 3)          # 9-atom 3x3 triangular lattice\n"
    "    rng = np.random.default_rng(1)\n"
    "    configs, energies = [], []\n"
    "    for _ in range(n_samples):\n"
    "        pos = base + noise_scale * rng.standard_normal(base.shape)\n"
    "        E = lj_energy(pos)\n"
    "        if abs(E) < 50:                      # skip unphysically compressed configs\n"
    "            configs.append(pos)\n"
    "            energies.append(E)\n"
    "    return np.array(configs), np.array(energies)\n"
    "\n"
    "X, y = make_dataset()\n"
    "print(f'dataset: {len(X)} configs of {X.shape[1]} atoms in {X.shape[2]}D')\n"
    "print(f'energy range: [{y.min():.2f}, {y.max():.2f}]')\n"
    "\n"
    "plt.figure(figsize=(6, 3))\n"
    "plt.hist(y, bins=40, edgecolor='k', lw=0.4)\n"
    "plt.xlabel('potential energy'); plt.ylabel('count')\n"
    "plt.title('Training energy distribution')\n"
    "plt.tight_layout(); plt.show()"
)

md(
    "## 2. Features: how to represent a configuration\n"
    "\n"
    "A plain neural network takes a fixed-size vector as input. "
    "But raw $(x, y)$ coordinates have a problem: if we rotate or translate the cluster, "
    "the energy should not change (physics is symmetric). "
    "A network trained on raw coordinates would have to learn that symmetry from scratch.\n"
    "\n"
    "The standard fix is to feed the network **pairwise distances** instead. "
    "Distances are invariant to translation and rotation. "
    "For $N$ atoms there are $N(N-1)/2$ unique pairs. We **sort** them so the representation "
    "is also invariant to the arbitrary ordering of atoms.\n"
    "\n"
    "> **Important:** because we sort, we must sort *everywhere* -- in training, in the energy, "
    "and in the force. The force path below sorts while keeping the autograd graph "
    "(`torch.sort` / a value-sorted `torch.stack` is differentiable), so the force is the "
    "gradient of exactly the same function we trained. This is a minimal but working feature "
    "set; Notebooks 04 and 05 replace it with smarter representations."
)

code(
    "def pairwise_distances(pos):\n"
    "    \"\"\"All pairwise distances for a single configuration, sorted ascending (numpy).\"\"\"\n"
    "    n = len(pos)\n"
    "    dists = []\n"
    "    for i in range(n):\n"
    "        for j in range(i + 1, n):\n"
    "            dists.append(np.linalg.norm(pos[i] - pos[j]))\n"
    "    return np.sort(dists)\n"
    "\n"
    "def pairwise_distances_torch(pos):\n"
    "    \"\"\"Same, for a torch (N, d) tensor, SORTED and keeping the autograd graph.\n"
    "\n"
    "    torch.sort is differentiable: it only permutes the values, so gradients flow\n"
    "    back to the original positions. Sorting here (not just in numpy) is what makes\n"
    "    the autograd force consistent with the sorted features the model was trained on.\n"
    "    \"\"\"\n"
    "    n = pos.shape[0]\n"
    "    dists = []\n"
    "    for i in range(n):\n"
    "        for j in range(i + 1, n):\n"
    "            diff = pos[i] - pos[j]\n"
    "            dists.append(torch.sqrt((diff * diff).sum()))\n"
    "    d = torch.stack(dists)\n"
    "    return torch.sort(d).values          # sorted, graph preserved\n"
    "\n"
    "X_feat = np.array([pairwise_distances(x) for x in X])\n"
    "print(f'feature shape: {X_feat.shape} (one sorted distance vector per config)')\n"
    "\n"
    "# Sanity: translation invariance\n"
    "pos_shifted = X[0] + np.array([100.0, 200.0])\n"
    "print('translation-invariant:', np.allclose(X_feat[0], pairwise_distances(pos_shifted)))\n"
    "\n"
    "# Sanity: the torch path matches the numpy path (both sorted)\n"
    "p = torch.tensor(X[0], dtype=torch.float64)\n"
    "print('torch path == numpy path:',\n"
    "      np.allclose(pairwise_distances_torch(p).detach().numpy(), X_feat[0]))"
)

md(
    "## 3. Build and train the network\n"
    "\n"
    "The network is a simple MLP: a few fully-connected layers with SiLU activations. "
    "We keep it small -- easier to debug and plenty for a 9-atom LJ system. "
    "The loss is mean squared error between predicted and true energies."
)

code(
    "class EnergyNet(nn.Module):\n"
    "    \"\"\"MLP that maps sorted pairwise distances -> potential energy.\"\"\"\n"
    "    def __init__(self, n_features, hidden=64):\n"
    "        super().__init__()\n"
    "        self.net = nn.Sequential(\n"
    "            nn.Linear(n_features, hidden), nn.SiLU(),\n"
    "            nn.Linear(hidden, hidden), nn.SiLU(),\n"
    "            nn.Linear(hidden, hidden), nn.SiLU(),\n"
    "            nn.Linear(hidden, 1),\n"
    "        )\n"
    "\n"
    "    def forward(self, x):\n"
    "        return self.net(x).squeeze(-1)\n"
    "\n"
    "n_train = int(0.8 * len(X_feat))\n"
    "idx = np.random.permutation(len(X_feat))\n"
    "train_i, val_i = idx[:n_train], idx[n_train:]\n"
    "\n"
    "X_tr = torch.tensor(X_feat[train_i], dtype=torch.float32)\n"
    "y_tr = torch.tensor(y[train_i], dtype=torch.float32)\n"
    "X_va = torch.tensor(X_feat[val_i], dtype=torch.float32)\n"
    "y_va = torch.tensor(y[val_i], dtype=torch.float32)\n"
    "\n"
    "model = EnergyNet(n_features=X_feat.shape[1])\n"
    "opt = torch.optim.Adam(model.parameters(), lr=3e-3)\n"
    "sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=500)\n"
    "\n"
    "train_losses, val_losses = [], []\n"
    "for epoch in range(500):\n"
    "    model.train(); opt.zero_grad()\n"
    "    loss = nn.functional.mse_loss(model(X_tr), y_tr)\n"
    "    loss.backward(); opt.step(); sched.step()\n"
    "    train_losses.append(loss.item())\n"
    "    model.eval()\n"
    "    with torch.no_grad():\n"
    "        val_losses.append(nn.functional.mse_loss(model(X_va), y_va).item())\n"
    "    if (epoch + 1) % 100 == 0:\n"
    "        print(f'epoch {epoch+1:4d}  train MSE={train_losses[-1]:.4f}  val MSE={val_losses[-1]:.4f}')\n"
    "\n"
    "plt.figure(figsize=(6, 3))\n"
    "plt.semilogy(train_losses, label='train')\n"
    "plt.semilogy(val_losses, label='val')\n"
    "plt.xlabel('epoch'); plt.ylabel('MSE loss (log)')\n"
    "plt.title('Training curve'); plt.legend()\n"
    "plt.tight_layout(); plt.show()"
)

md(
    "## 4. Forces from autograd\n"
    "\n"
    "To get forces from the network, we do NOT add a force output head. "
    "We differentiate the energy with respect to positions -- the same operation as the "
    "finite-difference check in Notebook 01, but exact and automatic.\n"
    "\n"
    "```python\n"
    "pos = torch.tensor(positions, requires_grad=True)\n"
    "feat = pairwise_distances_torch(pos)   # sorted, graph kept\n"
    "E = model(feat.unsqueeze(0))\n"
    "E.backward()                           # dE/d(pos)\n"
    "forces = -pos.grad                     # F = -dV/dr\n"
    "```\n"
    "\n"
    "Because the torch feature path sorts *with* the graph, this is the exact gradient of "
    "the same function the model was trained on. We confirm with the Notebook 01 gradient check."
)

code(
    "def nn_energy(pos_np):\n"
    "    \"\"\"Network energy for numpy positions (uses the sorted numpy features).\"\"\"\n"
    "    feat = torch.tensor(pairwise_distances(pos_np), dtype=torch.float32).unsqueeze(0)\n"
    "    model.eval()\n"
    "    with torch.no_grad():\n"
    "        return model(feat).item()\n"
    "\n"
    "def nn_forces(pos_np):\n"
    "    \"\"\"Forces via autograd (uses the sorted torch features -> consistent with nn_energy).\"\"\"\n"
    "    pos = torch.tensor(pos_np, dtype=torch.float32, requires_grad=True)\n"
    "    feat = pairwise_distances_torch(pos)          # (N*(N-1)/2,), sorted, graph kept\n"
    "    model.eval()\n"
    "    E = model(feat.unsqueeze(0))                  # (1,)\n"
    "    E.backward()\n"
    "    return -pos.grad.numpy()                      # F = -dE/dr\n"
    "\n"
    "# ---- Gradient check (same idea as Notebook 01) ----\n"
    "pos = triangular_lattice(3, 3) + 0.05 * np.random.randn(9, 2)\n"
    "analytic = nn_forces(pos)\n"
    "\n"
    "h = 1e-4\n"
    "numerical = np.zeros_like(pos)\n"
    "for i in range(pos.shape[0]):\n"
    "    for k in range(pos.shape[1]):\n"
    "        p_plus, p_minus = pos.copy(), pos.copy()\n"
    "        p_plus[i, k] += h\n"
    "        p_minus[i, k] -= h\n"
    "        numerical[i, k] = -(nn_energy(p_plus) - nn_energy(p_minus)) / (2 * h)\n"
    "\n"
    "max_err = np.max(np.abs(analytic - numerical))\n"
    "rel_err = max_err / (np.abs(numerical).max() + 1e-12)\n"
    "print(f'autograd vs numerical force:  max abs error {max_err:.4f},  relative error {rel_err:.2%}')\n"
    "print('They agree to well under a percent -- the autograd force IS the gradient of the energy.')\n"
    "print('The tiny residual is the non-differentiable points of sorting (two distances swapping')\n"
    "print('rank), which is exactly the non-smoothness Notebook 04 removes with symmetry functions.')\n"
    "\n"
    "# Note: the NN was trained on ENERGY only, so its forces need not match the true LJ forces\n"
    "# (energy-only training does not constrain the gradient). Adding forces to the loss fixes\n"
    "# this -- see Exercise 1. This is why we validate with energy conservation, not force accuracy.\n"
    "lj_F = lj_forces(pos)\n"
    "print(f'\\n(For contrast) NN vs true LJ force, max diff: {np.max(np.abs(nn_forces(pos) - lj_F)):.2f}'\n"
    "      '  <- large because training saw energies only, not forces')"
)

md(
    "## 5. Run MD with the learned potential\n"
    "\n"
    "Now we slot the neural-network forces into the same velocity-Verlet loop as Notebook 01. "
    "The only change is the force function. If the learned potential is physically reasonable, "
    "total energy should stay flat."
)

code(
    "def run_md_nn(positions, velocities, dt=0.004, steps=1000, mass=1.0, record_every=10):\n"
    "    \"\"\"MD loop using the neural-network force instead of LJ.\"\"\"\n"
    "    pos = np.asarray(positions, dtype=float).copy()\n"
    "    vel = np.asarray(velocities, dtype=float).copy()\n"
    "    forces = nn_forces(pos)\n"
    "    traj, pot, kin, tot = [], [], [], []\n"
    "    for step in range(steps):\n"
    "        if step % record_every == 0:\n"
    "            u = nn_energy(pos)\n"
    "            k = 0.5 * mass * np.sum(vel ** 2)\n"
    "            traj.append(pos.copy()); pot.append(u); kin.append(k); tot.append(u + k)\n"
    "        accel = forces / mass\n"
    "        v_half = vel + 0.5 * accel * dt\n"
    "        pos = pos + v_half * dt\n"
    "        forces = nn_forces(pos)\n"
    "        vel = v_half + 0.5 * (forces / mass) * dt\n"
    "    return dict(traj=np.array(traj), potential=np.array(pot),\n"
    "                kinetic=np.array(kin), total=np.array(tot))\n"
    "\n"
    "print('Running NN-MD (this may take ~30 seconds on CPU)...')\n"
    "start_pos = triangular_lattice(3, 3)\n"
    "start_vel = thermal_velocities(9, d=2, temp=0.1, seed=5)\n"
    "\n"
    "out_nn = run_md_nn(start_pos, start_vel, dt=0.003, steps=500, record_every=5)\n"
    "out_lj = run_md(start_pos, start_vel, dt=0.003, steps=500, record_every=5)\n"
    "\n"
    "nn_drift = (out_nn['total'].max() - out_nn['total'].min()) / abs(out_nn['total'].mean())\n"
    "lj_drift = (out_lj['total'].max() - out_lj['total'].min()) / abs(out_lj['total'].mean())\n"
    "print(f'NN total energy drift: {nn_drift:.3%}')\n"
    "print(f'LJ total energy drift: {lj_drift:.3%}')"
)

code(
    "t = np.arange(len(out_nn['total']))\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
    "for ax, (out, title) in zip(axes, [\n"
    "    (out_lj, 'Lennard-Jones (ground truth)'),\n"
    "    (out_nn, 'Neural-network potential (learned)'),\n"
    "]):\n"
    "    ax.plot(t, out['potential'], label='potential')\n"
    "    ax.plot(t, out['kinetic'], label='kinetic')\n"
    "    ax.plot(t, out['total'], lw=2.5, label='total (flat = honest)')\n"
    "    ax.set_xlabel('recorded step'); ax.set_ylabel('energy')\n"
    "    ax.set_title(title); ax.legend()\n"
    "plt.tight_layout(); plt.show()"
)

md(
    "## 6. What we built -- and what is still missing\n"
    "\n"
    "You replaced the hand-written force with a learned one. The MD loop is untouched. "
    "The energy-conservation check is the same. Everything you would do to validate a classical "
    "force field applies here too -- that is the point.\n"
    "\n"
    "**What we glossed over:**\n"
    "\n"
    "1. **Sorted distances lose information and are non-smooth.** Sorting is permutation-invariant, "
    "   but the sort order can switch as atoms move, putting kinks in the features. "
    "   Notebook 04 replaces sorted distances with smooth symmetry functions.\n"
    "\n"
    "2. **The network does not respect physical symmetries by construction.** "
    "   It must learn them from data, which needs far more data than an architecture that "
    "   encodes symmetry by design. Notebook 04 shows how.\n"
    "\n"
    "3. **There is no cutoff.** Real potentials only include atoms within a cutoff radius. "
    "   Our feature vector grows as $N^2$. Notebooks 04-05 fix this.\n"
    "\n"
    "4. **Silent failure is possible.** On a configuration far from the training set -- two atoms "
    "   too close, a species not in the data -- the network still returns a number, with no warning. "
    "   Notebook 07 is about catching exactly this.\n"
    "\n"
    "### Exercises\n"
    "\n"
    "1. **Force training.** Add forces to the loss: `loss = alpha * E_loss + beta * F_loss`. "
    "   How does including force labels change the MD quality?\n"
    "\n"
    "2. **Cutoff.** Modify `pairwise_distances` to only include pairs closer than `r_cut = 3.0`. "
    "   Does the model still work? Does training speed up?\n"
    "\n"
    "3. **Out-of-distribution check.** Evaluate `nn_energy` on a configuration with two atoms at "
    "   distance 0.5 (never in training). Compare to `lj_energy`. Is the prediction physical?"
)

nb.cells = cells
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "notebooks", "03_neural_network_potential_from_scratch.ipynb")
with open(OUT, "w") as f:
    nbf.write(nb, f)
print(f"wrote {OUT}")
